define('custom:views/quote/record/panels/finanziamento', ['views/record/panels/bottom'], function (Dep) {

    return Dep.extend({

        templateContent: [
            '<div class="row">',
            '  <div class="col-sm-6 cell form-group" data-name="finanziamento">',
            '    <label class="control-label" data-name="finanziamento">',
            '      <span class="label-text">{{translate "finanziamento" scope="Quote" category="fields"}}</span>',
            '    </label>',
            '    <div class="field" data-name="finanziamento">{{{var finanziamentoField this}}}</div>',
            '  </div>',
            '  <div class="col-sm-6 cell form-group" data-name="statoFinanziamento">',
            '    <label class="control-label" data-name="statoFinanziamento">',
            '      <span class="label-text">{{translate "statoFinanziamento" scope="Quote" category="fields"}}</span>',
            '    </label>',
            '    <div class="field" data-name="statoFinanziamento">{{{var statoFinanziamentoField this}}}</div>',
            '  </div>',
            '</div>',
            '<div class="row">',
            '  <div class="col-sm-6 cell form-group" data-name="importoCaparra">',
            '    <label class="control-label" data-name="importoCaparra">',
            '      <span class="label-text">{{translate "importoCaparra" scope="Quote" category="fields"}}</span>',
            '    </label>',
            '    <div class="field" data-name="importoCaparra">{{{var importoCaparraField this}}}</div>',
            '  </div>',
            '  <div class="col-sm-6 cell form-group" data-name="importoSaldo">',
            '    <label class="control-label" data-name="importoSaldo">',
            '      <span class="label-text">{{translate "importoSaldo" scope="Quote" category="fields"}}</span>',
            '    </label>',
            '    <div class="field" data-name="importoSaldo">{{{var importoSaldoField this}}}</div>',
            '  </div>',
            '</div>',
            '<div class="row">',
            '  <div class="col-sm-4 cell form-group" data-name="importoFinanziato">',
            '    <label class="control-label" data-name="importoFinanziato">',
            '      <span class="label-text">{{translate "importoFinanziato" scope="Quote" category="fields"}}</span>',
            '    </label>',
            '    <div class="field" data-name="importoFinanziato">{{{var importoFinanziatoField this}}}</div>',
            '  </div>',
            '  <div class="col-sm-4 cell form-group" data-name="rataPrestito">',
            '    <label class="control-label" data-name="rataPrestito">',
            '      <span class="label-text">{{translate "rataPrestito" scope="Quote" category="fields"}}</span>',
            '    </label>',
            '    <div class="field" data-name="rataPrestito">{{{var rataPrestitoField this}}}</div>',
            '  </div>',
            '  <div class="col-sm-4 cell form-group" data-name="nrRate">',
            '    <label class="control-label" data-name="nrRate">',
            '      <span class="label-text">{{translate "nrRate" scope="Quote" category="fields"}}</span>',
            '    </label>',
            '    <div class="field" data-name="nrRate">{{{var nrRateField this}}}</div>',
            '  </div>',
            '</div>',
            '<div class="row">',
            '  <div class="col-sm-6 cell form-group" data-name="tassoZero">',
            '    <label class="control-label" data-name="tassoZero">',
            '      <span class="label-text">{{translate "tassoZero" scope="Quote" category="fields"}}</span>',
            '    </label>',
            '    <div class="field" data-name="tassoZero">{{{var tassoZeroField this}}}</div>',
            '  </div>',
            '</div>',
        ].join('\n'),

        setupFields: function () {
            this.fieldList = [
                'finanziamento',
                'statoFinanziamento',
                'importoCaparra',
                'importoSaldo',
                'importoFinanziato',
                'rataPrestito',
                'nrRate',
                'tassoZero',
            ];
        },
    });
});
